version: '3'
services:

# nginx-1
  nginx-1:
    container_name: nginx-1
    image: nginx:latest
    ports:
      - 80:80
    volumes:
      - ./nginx/conf/defaut.conf:/etc/nginx/conf.d/default.conf
      - ./nginx/conf/nginx.conf:/etc/nginx/nginx.conf

# telegraf node 1 Log for Loki
  telegraf-loki:
    container_name: telegraf-loki
    image: telegraf:1.26.3
    # build: telegraf
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./test:/var/log/test # test input file
      - ./telegraf/conf/telegraf.loki.conf:/etc/telegraf/telegraf.conf
      - ./log.out:/tmp/log.out
    depends_on:
      - nginx-1
      - loki

# telegraf node 2 Metrics for Victoriametrics
  telegraf:
    container_name: telegraf-vm
    image: telegraf:1.26.3
    # build: telegraf
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./test:/var/log/test # test input file
      - ./telegraf/conf/telegraf.vm.conf:/etc/telegraf/telegraf.conf
      - ./log.out:/tmp/log.out
    depends_on:
      - nginx-1
      - victoriametrics

# loki
  loki:
    container_name: loki
    image: grafana/loki:2.8.2
    ports:
      - 3100:3100
    volumes:
      - loki-data:/loki
    command: -config.file=/etc/loki/local-config.yaml    

# victoriametrics
  victoriametrics:
    container_name: victoriametrics
    image: victoriametrics/victoria-metrics:v1.91.0
    ports:
      - 8428:8428
    volumes:
      - victoriametrics_data:/victoria-metrics-data
    command: -storageDataPath /victoria-metrics-data

# grafana
  grafana:
    container_name: grafana
    image: grafana/grafana:latest
    ports:
      - "3000:3000"
    environment:
      - GF_PATHS_PROVISIONING=/etc/grafana/provisioning
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
    entrypoint:
      - sh
      - -euc
      - |
        mkdir -p /etc/grafana/provisioning/datasources
        cat <<EOF > /etc/grafana/provisioning/datasources/ds.yaml
        apiVersion: 1
        datasources:
        - name: Loki
          type: loki
          access: proxy 
          orgId: 1
          url: http://loki:3100
          basicAuth: false
          isDefault: true
          version: 1
          editable: false
        EOF
        /run.sh

volumes:
  loki-data:
  victoriametrics_data: