version: '3'
services:

#nginx-1
  nginx-1:
    container_name: nginx-1
    image: nginx:latest
    ports:
      - 80:80
    volumes:
      # - loki-nginx-log-1:/var/log/nginx
      # - /var/run/docker.sock:/var/run/docker.sock
      - ./nginx/conf/defaut.conf:/etc/nginx/conf.d/default.conf:cache
      - ./nginx/conf/nginx.conf:/etc/nginx/nginx.conf

#telegraf
  telegraf:
    container_name: telegraf
    image: telegraf:1.26.3
    # build: telegraf
    volumes:
      # - loki-nginx-log-1:/var/log/nginx-1:cache
      - ./test:/var/log/test # test input file
      - /var/run/docker.sock:/var/run/docker.sock
      - ./telegraf/telegraf.d:/etc/telegraf/telegraf.d
      - ./telegraf/conf/telegraf.conf:/etc/telegraf/telegraf.conf
      - ./log.out:/tmp/log.out
    depends_on:
      - nginx-1
      - loki

#loki
  loki:
    container_name: loki
    image: grafana/loki:2.8.2
    ports:
      - 3100:3100
    volumes:
      - loki-data:/loki
    command: -config.file=/etc/loki/local-config.yaml    

  grafana:
    image: grafana/grafana:latest
    ports:
      - "3000:3000"
    environment:
      - GF_PATHS_PROVISIONING=/etc/grafana/provisioning
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
    entrypoint:
      - sh
      - -euc
      - |
        mkdir -p /etc/grafana/provisioning/datasources
        cat <<EOF > /etc/grafana/provisioning/datasources/ds.yaml
        apiVersion: 1
        datasources:
        - name: Loki
          type: loki
          access: proxy 
          orgId: 1
          url: http://loki:3100
          basicAuth: false
          isDefault: true
          version: 1
          editable: false
        EOF
        /run.sh
volumes:
  loki-data: